version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "monthly"
    versioning-strategy: "increase"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "development"
    ignore:
      - dependency-name: "symfony/cache"
      - dependency-name: "symfony/cache-contracts"
      - dependency-name: "symfony/messenger"
      - dependency-name: "doctrine/dbal"
      - dependency-name: "composer-runtime-api"
    groups:
        phpstan:
            patterns: ["*phpstan*"]
